name: Ashwin kumar
markdown: redcarpet
pygments: true

url: "http://ashwinkumar.me"
baseurl: "/"

permalink: /posts/:title
projects: /projects

description: "You will find my writings here. I love working on Product development and Software engineering."
keywords: "Writings, Startup engineering, Product development"
main_title: "Ashwin's playground"

google-analytics: "UA-38684144-1"


github: https://github.com/ashking
linkedin: http://www.linkedin.com/in/ashwinkumark
google: https://plus.google.com/104488956102051410647/posts
twitter: https://twitter.com/ashwinkumar_k
facebook: https://www.facebook.com/ashwinkumark10